paper:
	echo Latixing.. 
	latex paper.tex
	echo 
	echo ------------------------
	dvipdf paper.dvi
	echo ------------------------
	echo 
	evince paper.pdf

orig:
	latex orig.tex
	dvipdf orig.dvi
	evince orig.pdf

aacl:
	latex aacl-ijcnlp2020.tex
	dvipdf aacl-ijcnlp2020.dvi
	evince aacl-ijcnlp2020.pdf

